# Generated by Django 2.1 on 2020-09-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('editor', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('destacado', models.BooleanField(default=False)),
                ('tags', models.CharField(max_length=200)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('resumen', models.CharField(max_length=200)),
                ('detalle', models.CharField(max_length=200)),
            ],
        ),
    ]
