# Generated by Django 2.1 on 2020-09-05 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_news_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Noticias',
        ),
    ]
