# Generated by Django 2.1 on 2020-09-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_auto_20200909_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='detalle',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='resumen',
            field=models.CharField(max_length=250),
        ),
    ]
